# Generated by Django 5.2.1 on 2025-07-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_attendee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
